version: '3.9'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    # build:
    #   context: .
    #   dockerfile: keycloak.Dockerfile
    restart: always
    environment:
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false

      KC_DB_URL_HOST: kc_database
      KC_DB_URL_PORT: 5432
      
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASS}

      # KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      JAVA_OPTS: -Djboss.bind.address.private=127.0.0.1 -Djboss.bind.address=0.0.0.0
    depends_on:
      - kc_database
    ports:
      - "${KEYCLOAK_PORT}:8080"
    command: ["start", "--cache=ispn"]
    networks:
      - local-keycloak

  kc_database:
    container_name: kc_database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - kc_pgdata:/var/lib/postgresql/data
    networks:
      - local-keycloak

volumes:
  kc_pgdata:
    name: kc_pgdata

networks:
  local-keycloak:
    name: local-keycloak